[project]
name = "tech-updates-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bs4>=0.0.2",
    "mcp[cli]>=1.9.1",
    "requests>=2.32.3",
]
